defaultPlacement: end
enableVersioning: true
entryTypes:
  - 4a77ed54-0ba5-4d81-b23a-0db2319a59b2 # Post
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1621314b-c664-4a2c-8247-16b9c690c79a: # tutorial
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
